[package]
name = "crates_io_spider"
version = "0.1.1"
authors = ["wangkirin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates_io_api = "0.6.1"